# Generated by Django 2.2.3 on 2019-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(default='United Kingdom', max_length=120)),
                ('post_code', models.CharField(max_length=200)),
                ('address_label', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('sage_customer_id', models.CharField(max_length=50)),
                ('address', models.ManyToManyField(to='customer.Address', verbose_name='Addresses')),
            ],
        ),
    ]
