# Generated by Django 2.2.3 on 2019-11-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_label',
            field=models.BooleanField(default=False, help_text='if ticked, address will be used for label'),
        ),
    ]
