# Generated by Django 2.2.3 on 2019-11-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191108_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_label',
        ),
    ]
