# Generated by Django 2.2.3 on 2019-11-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brand_color', models.CharField(help_text='HEX colour', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(max_length=10)),
                ('component_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PalletInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_per_carton', models.PositiveIntegerField()),
                ('cartons_per_layer', models.PositiveIntegerField()),
                ('units_per_layer', models.PositiveIntegerField()),
                ('layers_per_pallet', models.PositiveIntegerField()),
                ('units_per_pallet', models.PositiveIntegerField()),
                ('cartons_per_pallet', models.PositiveIntegerField()),
                ('carton_weight', models.PositiveIntegerField(help_text='Only Integers. Unit=KG')),
                ('carton_dimensions', models.PositiveIntegerField(help_text='Format= L x W x H , Unit=CM')),
                ('pallet_weight_gross', models.PositiveIntegerField(help_text='Unit=KG')),
                ('pallet_size', models.PositiveIntegerField(help_text='Format= L x W x H , Unit=CM')),
                ('pallet_type', models.CharField(choices=[('ST', 'STANDARD'), ('EU', 'EUROPE')], default='ST', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('option_name', models.CharField(max_length=20)),
                ('option_value', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('barcode_number', models.PositiveIntegerField()),
                ('box_of_6', models.PositiveIntegerField()),
                ('unit_dimensions', models.CharField(help_text='Format= L x W x H , Unit=CM', max_length=100)),
                ('unit_weight', models.PositiveIntegerField(help_text='Unit=KG')),
                ('date_first_available', models.DateField()),
                ('discontinued', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('bills_of_component', models.ManyToManyField(blank=True, to='pif.Component')),
                ('pallet_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pif.PalletInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pif.Brand')),
                ('variant', models.ManyToManyField(blank=True, to='pif.ProductVariant')),
            ],
        ),
    ]
