# Generated by Django 2.2.3 on 2019-11-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='pallet_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pif.PalletInformation'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit_weight',
            field=models.IntegerField(help_text='Unit=KG'),
        ),
    ]
