# Generated by Django 2.2.3 on 2019-11-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('pif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('mfg_date', models.DateField(blank=True, help_text='For coding only', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='For coding only', null=True)),
                ('notes', models.TextField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant', to='pif.ProductVariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prf_number', models.IntegerField()),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('required_date', models.DateField(auto_now_add=True)),
                ('expected_completion_date', models.DateField(auto_now_add=True, null=True)),
                ('expiry_date_format', models.CharField(blank=True, max_length=10, null=True)),
                ('shrink_wrap', models.CharField(blank=True, choices=[('ST', 'STANDARD CLEAR'), ('BL', 'Black'), ('ST', 'Security Tape')], max_length=2, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PE', 'Pending'), ('OP', 'Open'), ('RE', 'Reviewing'), ('OH', 'On-Hold'), ('AI', 'Awaiting Information'), ('PR', 'In progress'), ('CO', 'Complete')], max_length=2, null=True)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('request_type', models.ManyToManyField(blank=True, to='web.RequestType')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
