# Generated by Django 2.2.3 on 2019-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='table_row',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='productionlist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
