# Generated by Django 2.2.3 on 2019-11-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='production_list',
            field=models.ManyToManyField(blank=True, to='web.ProductionList'),
        ),
    ]
