# Generated by Django 2.2.3 on 2019-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='productionjob',
            name='address_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='customer_address_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='required_date',
            field=models.DateField(),
        ),
    ]
