# Generated by Django 2.2.3 on 2019-11-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_modelchangelogsmodel_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='table_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='table_name',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
    ]
